title: Dr Nishtha Chopra 
email: nishtha50376@gmail.com
description: >- 
  Space to explore optics research, consulting work, and science communication.
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
