title: Dr Nishtha Chopra 
email: nishtha50376@gmail.com
description: Optical systems & photonics R&D â€” from models to prototypes.
header_pages:
  - research.md
  - concepts.md
  - about.md
  - contact.md
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
